spring:
  application:
    name: zuulapp
server:
  servlet:
    contextPath: /zuulapi
zuul:
  host:
    connect-timeout-millis: 1080000
    socket-timeout-millis: 1080000
  routes:
     helloservice:
      path: /helloservice/**
      url: https://hello-service-6xgn7czs6q-uc.a.run.app
      strip-prefix: false
